tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "kayac/tap"

brew "ansible"
brew "awscli"
brew "eksctl"
brew "gh"
brew "gibo"
brew "git"
brew "git-lfs"
brew "go"
brew "helm"
brew "htop"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "kustomize"
brew "mysql-client"
brew "openssl"
brew "pyenv"
brew "terraform"
brew "tmux"

brew "kayac/tap/ecspresso"

cask "docker"
cask "iterm2"
cask "postman"
cask "visual-studio-code"
